<?php
require_once __DIR__ . '/include/auth.php';
$user = iqac_require_login(['staff', 'tutor', 'hod', 'iqac', 'admin', 'super_admin']);
$rows = [];
if (iqac_table_exists($conn, 'student_achievements')) {
    $rows = $conn->query('SELECT sd.full_name, sd.roll_number, sa.title AS achievement_title, sa.achievement_type, sa.achievement_date, sa.status FROM student_achievements sa JOIN student_details sd ON sd.student_id = sa.student_id ORDER BY sa.achievement_date DESC, sa.id DESC')->fetch_all(MYSQLI_ASSOC);
} elseif (iqac_table_exists($conn, 'achievement_details')) {
    $rows = $conn->query('SELECT sd.full_name, sd.roll_number, ach.achievement_title, ach.achievement_level AS achievement_type, ach.date_awarded AS achievement_date, "recorded" AS status FROM achievement_details ach JOIN student_details sd ON sd.student_id = ach.student_id ORDER BY ach.date_awarded DESC, ach.id DESC')->fetch_all(MYSQLI_ASSOC);
}
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>Achievements NBA Report</title><style>
body{background:#fff;color:#000;font-family:Arial,sans-serif}.shell{max-width:1050px;margin:auto;padding:22px}.head{text-align:center;border:1px solid #000;padding:10px}.head h1{font-size:20px;margin:0}.head h2{font-size:16px;margin:4px 0}table{width:100%;border-collapse:collapse;font-size:12px;margin-top:12px}td,th{border:1px solid #000;padding:6px;text-align:center}td:first-child,th:first-child{text-align:left}.sign{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;margin-top:32px;font-size:12px}.sign div{border-top:1px solid #000;text-align:center;padding-top:8px}.footer{border-top:1px solid #000;margin-top:14px;padding-top:6px;display:flex;justify-content:space-between;font-size:11px}@media print{@page{size:A4 portrait;margin:10mm}.no-print{display:none}.footer{position:fixed;bottom:0;left:10mm;right:10mm}.page:after{content:counter(page)}}
</style></head><body><div class="shell"><p class="no-print"><button onclick="window.print()">Print / PDF</button> <a href="academic_erp.php">Dashboard</a></p><div class="head"><h1>PSG POLYTECHNIC COLLEGE</h1><h2>DEPARTMENT OF <?= htmlspecialchars($_GET['department'] ?? 'ALL') ?></h2><h2>NBA ACCREDITATION REPORT - STUDENT ACHIEVEMENTS</h2><table><tr><td>Academic Year</td><td><?= htmlspecialchars($_GET['academic_year'] ?? '') ?></td><td>Semester</td><td><?= htmlspecialchars($_GET['semester'] ?? 'All') ?></td></tr><tr><td>Batch</td><td><?= htmlspecialchars($_GET['batch'] ?? 'All') ?></td><td>Generated Date</td><td><?= date('Y-m-d H:i:s') ?></td></tr><tr><td>Prepared By</td><td><?= htmlspecialchars($user['username']) ?></td><td>Verified By</td><td></td></tr><tr><td>Approved By</td><td></td><td>Page No</td><td><span class="page"></span></td></tr></table></div><table><thead><tr><th>Student</th><th>Roll Number</th><th>Achievement</th><th>Type / Level</th><th>Date</th><th>Status</th></tr></thead><tbody><?php if(!$rows): ?><tr><td colspan="6">No records available.</td></tr><?php endif; ?><?php foreach($rows as $r): ?><tr><td><?= htmlspecialchars($r['full_name']) ?></td><td><?= htmlspecialchars($r['roll_number']) ?></td><td><?= htmlspecialchars($r['achievement_title']) ?></td><td><?= htmlspecialchars((string)$r['achievement_type']) ?></td><td><?= htmlspecialchars((string)$r['achievement_date']) ?></td><td><?= htmlspecialchars((string)$r['status']) ?></td></tr><?php endforeach; ?></tbody></table><div class="sign"><div>Prepared By Signature</div><div>Tutor Signature</div><div>Faculty Signature</div><div>HOD Signature</div><div>Principal Signature</div></div><div class="footer"><span>College Seal Area</span><span>Generated Timestamp: <?= date('Y-m-d H:i:s') ?></span></div></div></body></html>
